### ISSUE TITLE
Update "amount" names

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#318]
- [x] At common: keep it as it is, except for:
   - [x]  `LoadAmount` ==> `DepositAmount`. Implemented at #329 
- [x] At API: 
   - [x]  `loadAmount` ==> `depositAmount`. Implemented at #329 
   - [x] add `amountSuccess` and `depositAmountSuccess`. Implemented at #338 
- [x] At HistoryDB:
    - [x] Change `effective` (type `BYTEA`) for `success` (type `BOOL`). Implemented at #326
    - [x] Try to do negated logic to avoid unnecesary updates (only update in case some of the amounts hasn't been effective). Implemented at #326
    - [x] Return `big.Int` typed effective amounts for coordinator. Implemented at #326
    - [x] Return `bool` typed flags for success amounts in API. Implemented at #338
