### ISSUE TITLE
[AtomicTx] TxProcessor + ZKInputs fields

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#768]
## Rationale

To process and forge the atomic transactions, we will collect fees for a group of atomic transactions. Only one transaction is sufficient to pay the fee for all other transactions. We must calculate the sum of the fees and check if it reaches the `MinFeeUSD` parameter from the node. 

Also, we must create the ZKInputs fields for atomic transactions. Adding the data from another atomic transaction (`rqTxCompressedDataV2`), recipient addresses (`rqToEthAddr`/`rqToBjjAy`), and the offset position (`rqOffset`) into the batch of another atomic transaction linked following the `rqTxOffset` table.

Atomic Transaction parameters:
```yaml
rqOffset: relative transaction position to be linked. Used to perform atomic transactions (3 bits)
rqTxCompressedDataV2: requested txCompressedDataV2
rqToEthAddr: requested toEthAddr
rqToBjjAy: requested toBjj
```

rqTxOffset table:
| rqTxOffset |     relativeIndex     |
|:----------:|:---------------------:|
|     0      | no linked transaction |
|     1      |           1           |
|     2      |           2           |
|     3      |           3           |
|     4      |          -4           |
|     5      |          -3           |
|     6      |          -2           |
|     7      |          -1           |

rq-tx-verifier circuit:
https://docs.hermez.io/#/developers/protocol/hermez-protocol/circuits/circuits?id=rq-tx-verifier

## Implementation

- Add the atomic transaction fields based on the choose transaction from the `TxSelector`:
https://github.com/hermeznetwork/hermez-node/blob/e4ad3fab28d07368f1e4129878706ff141d32673/txprocessor/txprocessor.go#L787-L791

- Associate one each other by the `rqOffset` parameter; 

- Check if the sum of the fee is greater than the node `MinFeeUSD` parameter;

### Assumptions

- The transaction comes already sorted by position from the `TxSelector`;
- The total fee must be a sum of all transactions fee;
- The user can be the owner of all transactions and send all of them already signed;
- User A can make a simple transfer to user B and pay the fee using another token;
- `rqTxID` must be a valid `TxID`;

### TODOs

- [x] Group atomic transactions;
- [ ] Add ZKInputs fields;
- [x] Validate the group of transactions;
- [x] Collect fee from a group of transactions;

**Comment by arnaubennassar** [comment]
Closed in #860
