### ISSUE TITLE
[AtomicTx] API endpoint

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#769]
## Rationale

We must create a new API for the node to receive these transactions and validate them. The API must validate, also, the group of transactions together. One of these transactions can spend from another atomic transaction, from an account without balance before this transaction. The user must batch all signed transactions in the same request to broadcast all of them to be atomic.

## Implementation

We will create a new API method for sending atomic transactions called `atomic-pool`. This API must receive an array of transactions and validate all, also. If the sum of the fees is greater than the minimum node fee after, it will add the transaction into the `tx_pool` database, linking each other by the TxID. We must update the swagger files as well.

e.g.:

```bash
$ curl -X POST "<http://localhost:8086/v1/atomic-pool>" \
-H  "Content-Type: application/json" \
-d '[
  {
    "id": "0x029761c516998ab5261ca388574e5442ff926ce19ff2497e646f6bd58d66669b85",
    "type": "Transfer",
    "tokenId": 0,
    "fromAccountIndex": "hez:ETH:1276",
    "toAccountIndex": "hez:ETH:256",
    "toHezEthereumAddress": "hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF",
    "toBjj": "hez:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "amount": "10",
    "fee": 126,
    "nonce": 53,
    "signature": "494658979f0b4c93081a8aa6fd798c9b895c72b60cd3882a46339c564319a22a633d7a148b0cd25da537879478876204486dc38a3dcf0ce1b5717cbbbac56a02"
  },
  {
    "id": "0x0252222e0de00610eb3d32a3cbe72020ab8810c3518140e3bf82f1be663b26f1d2",
    "type": "Transfer",
    "tokenId": 1,
    "fromAccountIndex": "hez:ETH:256",
    "toAccountIndex": "hez:ETH:1276",
    "toHezEthereumAddress": "hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF",
    "toBjj": "hez:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "amount": "5",
    "fee": 126,
    "nonce": 30,
    "signature": "494658979f0b4c93081a8aa6fd798c9b895c72b60cd3882a46339c564319a22a633d7a148b0cd25da537879478876204486dc38a3dcf0ce1b5717cbbbac56a02"
  }
]'
```

### Assumptions

- All transaction must be signed by the destination address from itself;
- The endpoint `/atomic-pool` do not accept single transactions;
- All transactions sent into the endpoint `/atomic-pool` must have the same transaction validations into the pool, besides the fee;
- The total fee must be a sum of all transactions fee;
- The user can be the owner of all transactions and send all of them already signed;
- User A can make a simple transfer to user B and pay the fee using another token;
- `rqTxID` must be a valid `TxID`;
- The `rq` fields will be filled by the node;
- The transactions do not know about others in the protocol level, only in the node was broadcasted;

### TODOs

- [ ] Create new API method;
- [ ] Add transaction validations;
- [ ] Insert into the database;
- [ ] Calculate the fee from all tx's together;
- [ ] Update swagger files;

**Comment by arnaubennassar** [comment]
Closing as this is already merged on the branch `feature/atomic-tx`
