### ISSUE TITLE
[TxSelector] Refactor

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#776]
## Rationale

The current `TxSelector` is simple regarding architecture but complex regarding the code. If you check the cyclomatic and ABC complexities list in the final of this issue, the most complex methods are `getL1L2TxSelection`, `processL2Txs`, and `processTxToEthAddrBJJ`. These methods must be split into small extensions more testable. The current implementation has too many external function calls and conditions, making the tests harder to create. We must create a table test covering all of the possible conditions: errors and success.

For we can efficiently forge all transactions, the `TxSelector` will split transactions by group, called `TxGroup`. One single transaction can fit in one `TxGroup` if it doesn't have other transaction dependencies, and this group will use only one position into the batch for only one transaction. A group of atomic transactions can fit into the same `TxGroup` too if depends on one each other, and the node must forge the entire group if not, all transaction will fail.

## Implementation

The `TxGroup` must respect the structure below:

```go
type TxGroup struct {
	L1CoordTxs    []common.L1Tx // L1 coordinator transactions slice
	L2Txs         []common.L2Tx // L2 transactions slice
	FeeUSD        big.Int       // The sum of all collected fees in USD
	Atomic        bool          // The group created to handle atomic transactions
	FirstPosition uint          // First transaction position in the batch
}
```

Also, the `TxGroup` can group transactions by the same destination address for a better nonce and fee management:

```go
type TxGroup interface {
	// CreateCoordTxs build all coordinators transactions for we can put in the same group
	CreateCoordTxs() error
	// AddPositions add batch positions into the transactions
	AddPositions(firstIndex uint)
	// Validate validates all transactions into a batch, checking balances, fees, nonce, token id, and signatures
	Validate(acc []Account) error
	// CalculateFee calculate the fee average summing all transactions and divide by the number of transactions
	CalculateFee() (*big.Int, error)
	// Cmp compare two different groups and return what's groups have a preference for the next batch
	Cmp(group *TxGroup) int
	// Prune prune non-profitable transactions from the group if possible
	Prune() error
}
```

### TODOs

- [x] Core structure;
- [x] Create coordinator transactions extension;
- [x] Add the batch position extension and sort by the most profitable and the newest group first;
- [x] The transactions into the group must be sorted by nonce and fee;
- [x] Validate transactions extension;
- [x] Group transaction by the same destination address for a better nonce and fee management;
- [x] If a group don't fit in the batch because one position or more is missing, the node will forge the group in the next batch;

![Untitled Diagram-Page-1](https://user-images.githubusercontent.com/2406457/116758143-dae55680-a9e5-11eb-8fb9-ae8385d1c627.png)

- [x] Calculate fee by `TxGroup`. The transactions that fit into the batch must be the most profitable from the transaction pool. We must choose a group of transactions by the fee average. The sum of all fees divides by the number of transactions, like the schema below. Calling the `Prune()` method, we are going to prune this non-profitable transaction from the group;

![Untitled Diagram-Page-2 (1)](https://user-images.githubusercontent.com/2406457/116758123-d620a280-a9e5-11eb-96e7-d7af5677aee5.png)

### [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity)

**Complexity below using the [gocycle](https://github.com/fzipp/gocyclo):**

```
31 txselector (*TxSelector).processL2Txs          txselector/txselector.go:334:1
20 txselector (*TxSelector).getL1L2TxSelection    txselector/txselector.go:161:1
16 txselector (*TxSelector).processTxToEthAddrBJJ txselector/txselector.go:579:1
8  txselector checkPendingToCreateFutureTxs       txselector/txselector.go:723:1
5  txselector splitL2ForgableAndNonForgable       txselector/txselector.go:760:1
5  txselector checkPendingToCreateL1CoordTx       txselector/txselector.go:711:1
4  txselector (*TxSelector).coordAccountForTokenID txselector/txselector.go:85:1
2  txselector  NewTxSelector                      txselector/txselector.go:41:1
1  txselector (*TxSelector).GetL1L2TxSelection    txselector/txselector.go:143:1
1  txselector (*TxSelector).GetL2TxSelection      txselector/txselector.go:125:1
1  txselector (*TxSelector).Reset                 txselector/txselector.go:69:1
1  txselector (*TxSelector).getCoordIdx           txselector/txselector.go:73:1
1  txselector sortL2Txs                           txselector/txselector.go:741:1
1  txselector (*TxSelector).LocalAccountsDB       txselector/txselector.go:63:1
```

### [ABC Software Metric](https://en.wikipedia.org/wiki/ABC_Software_Metric)

**TxSelector ABC metrics generated by [abcgo](https://github.com/droptheplot/abcgo):**

```
Source              Func                            Score   A    B    C
txselector.go:41    NewTxSelector                   2       1    2    1
txselector.go:63    LocalAccountsDB                 0       0    0    0
txselector.go:69    Reset                           2       0    2    0
txselector.go:73    getCoordIdx                     1       0    1    0
txselector.go:85    coordAccountForTokenID          6       2    6    2
txselector.go:125   GetL2TxSelection                3       1    3    0
txselector.go:143   GetL1L2TxSelection              3       1    3    0
txselector.go:161   getL1L2TxSelection              84      36   73   23
txselector.go:334   processL2Txs                    96      51   64   51
txselector.go:579   processTxToEthAddrBJJ           40      7    27   29
txselector.go:711   checkPendingToCreateL1CoordTx   6       2    1    6
txselector.go:723   checkPendingToCreateFutureTxs   11      2    1    11
txselector.go:741   sortL2Txs                       2       0    2    2
txselector.go:760   splitL2ForgableAndNonForgable   11      8    8    3
```

**Comment by arnaubennassar** [comment]
Closing as this is already merged
