### ISSUE TITLE
Add missing tests for atomic txs

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#890]
## Rationale

Add tests for atomic transactions related cases.

Unit tests for `txselector`:

- [x] Select valid atomic groups (#894)
- [x] Discard invalid atomic groups, while keeping valid atomic and non atomic txs (#894)
- [x] Unit test for the new sort algorithm that takes into consideration atomic txs (specially check that the order within atomic groups is preserved, right now this is an asumption) (#894)

ZKI tests:

- [ ] All the tests from compatibility canary
